doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        # configure these for your database server
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
      customer:
        # configure these for your database server
        url: '%env(resolve:DATABASE_URL_TEST)%'
        driver: 'pdo_mysql'
  orm:
    default_entity_manager: default
    auto_generate_proxy_classes: true
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          App:
            is_bundle: false
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
      customer:
        connection: customer
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
